bookings/urls.py
from django.urls import path
from .views import (
    AddBookingView,
    ListBookingView,
    EditBookingView,
    DeleteBookingView
)

urlpatterns = [
    path("", AddBookingView.as_view(), name="add_booking"),
    path("list_bookings/", ListBookingView.as_view(), name="list_bookings"),
    path("edit/<slug:pk>/", EditBookingView.as_view(), name="edit_booking"),
    path("delete/<slug:pk>/",
         DeleteBookingView.as_view(),
         name="delete_booking"),
]

home/urls.py
from django.urls import path
from .views import Index

urlpatterns = [path("", Index.as_view(), name="home")]

main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("home.urls")),
    path("bookings/", include("bookings.urls")),
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User


NUM_SEATS = ((2, "2"), (4, "4"), (6, "6"), (8, "8"), (10, "10"), (12, "12"))
TIME_SLOTS = (
    (1, "13:00 - 15:00"),
    (2, "15:00 - 17:00"),
    (3, "17:00 - 19:00"),
    (4, "19:00 - 21:00"),
    (5, "21:00 - 23:00"),
)


class Table(models.Model):
    """model for restaurant table"""

    table_number = models.IntegerField(unique=True)
    table_num_seats = models.IntegerField(choices=NUM_SEATS, default=2)

    class Meta:
        ordering = ["table_number"]

    def __str__(self):
        return str(self.table_number)


class Booking(models.Model):
    """model for restaurant Bookings"""

    cust = models.ForeignKey(
        User, related_name="booking_owner", on_delete=models.CASCADE
    )
    cust_name = models.CharField(max_length=50)
    booking_party_size = models.IntegerField(default=2)
    booking_date = models.DateField()
    booking_time = models.IntegerField(choices=TIME_SLOTS, default=1)
    booking_table = models.ForeignKey(
        Table, on_delete=models.CASCADE, related_name="table"
    )
    timestamp_booking_made = models.DateTimeField(auto_now=True)
    booking_notes = models.CharField(max_length=1000, null=True)

    class Meta:
        """Order by booking_date and then booking_time"""

        ordering = ["booking_date", "booking_time"]

    def __str__(self):
        return str(self.pk)

bookings/forms.py
from datetime import datetime
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django import forms
from .models import Booking, Table
from .widgets import DatePickerInput


class BookingForm(forms.ModelForm):
    """form to create a booking"""

    class Meta:
        model = Booking
        fields = [
            "cust_name",
            "booking_party_size",
            "booking_date",
            "booking_time",
        ]
        widgets = {
            "booking_date": DatePickerInput(),
        }
        labels = {
            "cust_name": "Name",
            "booking_party_size": "Party Size",
            "booking_date": "Date",
            "booking_time": "Time",
        }

    def clean(self):
        """
        Get form data and clean, check capacity and
        throw errors when tables not available
        """
        date = self.cleaned_data["booking_date"]
        time = self.cleaned_data["booking_time"]
        guests = self.cleaned_data["booking_party_size"]

        table_booked = None

        # Try and get object, as needed for update validation
        # pass error if on create

        try:
            table_booked = Table.objects.get(id=self.instance.booking_table.id)
        except ObjectDoesNotExist:
            pass

        # Filter tables with capacity greater or equal
        # to the number of guests
        bookings_on_requested_date = Booking.objects.filter(
            booking_date=date, booking_time=time
        )

        # Get bookings on specified date
        tables_big_enough = list(
            Table.objects.filter(table_num_seats__gte=guests))

        # Iterate over tables not booked to get lowest
        # capacity table
        for booking in bookings_on_requested_date:
            for table in tables_big_enough:
                if table.table_number == booking.booking_table.table_number:
                    tables_big_enough.remove(table)
                    break

        # Add booked table to list of tables
        if table_booked is not None:
            if table_booked.table_num_seats >= guests:
                tables_big_enough.append(table_booked)

        # Throw validation errors on form
        if date < datetime.today().date():
            raise ValidationError(
                "Invalid date - Booking cannot be in the past")

        if table_booked is not None:
            if not tables_big_enough and table_booked.table_num_seats < guests:
                raise ValidationError(
                    "Sorry, we do not have a table"
                    + " available for that amount of guests"
                )

        if not tables_big_enough:
            raise ValidationError("No tables available for this date and time")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["booking_date"].widget = forms.widgets.DateInput(
            attrs={"type": "date", "class": "form-control"}
        )

bookings/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from datetime import timedelta, date
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from .models import Booking, Table
from .forms import BookingForm
from django.db.models import Q


class DeleteBookingView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """Delete Booking"""

    model = Booking
    success_url = "/bookings/list_bookings/"

    def form_valid(self, form):
        messages.success(self.request, "Booking deleted.")
        return super(DeleteBookingView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_staff or \
            self.request.user == self.get_object().cust


class EditBookingView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """ " Edit Booking"""

    template_name = "bookings/edit_booking.html"
    model = Booking
    success_url = "/bookings/list_bookings/"
    form_class = BookingForm

    def form_valid(self, form):
        form.instance.cust = self.request.user
        """
        find the smallest free table for this party
        """
        date = form.cleaned_data["booking_date"]
        time = form.cleaned_data["booking_time"]
        party_size = form.cleaned_data["booking_party_size"]
        # get tables big enough for party
        suitable_tables = list(Table.objects.filter(
            table_num_seats__gte=party_size))

        # get the booking for that day
        bookings_on_date = Booking.objects.filter(
            booking_date=date, booking_time=time)

        # find free tables
        for booking in bookings_on_date:
            for table in suitable_tables:
                if table.table_number == booking.booking_table.table_number:
                    suitable_tables.remove(table)
                    break

        # get smallest free table for this booking
        smallest_suitable_table = suitable_tables[0]
        for table in suitable_tables:
            if table.table_num_seats < smallest_suitable_table.table_num_seats:
                smallest_suitable_table = table
        form.instance.booking_table = smallest_suitable_table

        messages.success(self.request, "Booking updated.")
        return super(EditBookingView, self).form_valid(form)

    def test_func(self):
        return self.request.user.is_staff or \
            self.request.user == self.get_object().cust


class ListBookingView(LoginRequiredMixin, ListView):
    """view for list of bookings"""

    template_name = "bookings/list_bookings.html"
    model = Booking
    context_object_name = "list_bookings"

    def get_queryset(self):
        """Queryset function for manage booking search"""
        query = self.request.GET.get("ref")
        dates = self.request.GET.get("date")
        names = self.request.GET.get("name")
        if names:
            return Booking.objects.filter(Q(cust_name__iregex=names))
        if query:
            return Booking.objects.filter(id=query)
        if dates:
            return Booking.objects.filter(booking_date=dates)
        if self.request.user.is_staff:
            # bookings today or later
            return Booking.objects.filter(booking_date__gte=(date.today()))
        else:
            # this customers bookings today or later
            return Booking.objects.filter(
                cust=self.request.user, booking_date__gte=(date.today())
            )


class AddBookingView(LoginRequiredMixin, CreateView):
    """Add Booking View"""

    template_name = "bookings/add_booking.html"
    model = Booking
    form_class = BookingForm
    success_url = "/bookings/list_bookings/"

    def form_valid(self, form):
        form.instance.cust = self.request.user
        """
        find the smallest free table for this party
        """
        date = form.cleaned_data["booking_date"]
        time = form.cleaned_data["booking_time"]
        party_size = form.cleaned_data["booking_party_size"]
        # get the bookings for that day /
        bookings_on_date = Booking.objects.filter(
            booking_date=date, booking_time=time)

        # get tables big enough for party
        suitable_tables = list(Table.objects.filter(
            table_num_seats__gte=party_size))

        # find free tables
        for booking in bookings_on_date:
            for table in suitable_tables:
                if table.table_number == booking.booking_table.table_number:
                    suitable_tables.remove(table)
                    break

        # get smallest free table for this booking
        smallest_suitable_table = suitable_tables[0]
        for table in suitable_tables:
            if table.table_num_seats < smallest_suitable_table.table_num_seats:
                smallest_suitable_table = table
        form.instance.booking_table = smallest_suitable_table

        messages.success(
            self.request, f"Booking confirmed for {party_size} on {date}")
        return super(AddBookingView, self).form_valid(form)

bookings/templates/bookings/add_booking.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Make a Booking{% endblock %}

{% block content %}

<div class="container">
    <form method='POST' enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Make a Booking</h1>
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-danger mt-2 w-20">Save Booking</button>
        </div>
    </form>
</div>
{% endblock %}

bookings/templates/bookings/booking_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static '/bookings/css/bookings.css' %}">
{% endblock %}

{% block title %}Delete Booking{% endblock %}
{% block content %}


<div class="container">
    <h1 class="text-center mt-2">Confirm Deletion</h1>
    <div class="d-flex justify-content-center pt-3">
        <form method='post' class="text-center">
            {% csrf_token %}
            <div class="card-container px-2 m-0">
                <div class="custom-card m-1 p-0">
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Date:</p>
                        <button class="m-1 w-50">{{ booking.booking_date }}</button>
                    </div>
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Time:</p>
                        <button class="m-1 w-50">{{ booking.get_booking_time_display }}</button>
                    </div>
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Ref:</p>
                        <button class="m-1 w-50">{{ booking.pk }}</button>
                    </div>
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Party of:</p>
                        <button class="m-1 w-50">{{ booking.booking_party_size }}</button>
                    </div>
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Name:</p>
                        <button class="m-1 w-50">{{ booking.cust_name }}</button>
                    </div>
                    {% if request.user.is_staff %}
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Table:</p>
                        <button class="m-1 w-50">{{ booking.booking_table }}</button>
                    </div>
                    <div class="card-row">
                        <p class="ms-1 mt-1 mb-0 fw-bold">Capacity:</p>
                        <button class="m-1 w-50">{{ booking.booking_table.table_num_seats }}</button>
                    </div>
                    {% endif %}
                </div>
            </div>
            <input type="submit" value="Confirm" class="btn btn-danger w-50 px-5">
        </form>
    </div>
</div>

{% endblock %}

bookings/templates/bookings/edit_booking.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Edit Booking{% endblock %}

{% block content %}

<div class="container">
    <form method='POST' enctype="multipart/form-data" class="p-2 form">
        <h1 class="text-center">Edit</h1>
        {% csrf_token %}
        {{ form.media }}
        {{ form|crispy }}
        <div class="text-center">
            <button type="submit" class="btn btn-danger mt-2 w-20">Save</button>
        </div>
    </form>
</div>
{% endblock %}

bookings/templates/bookings/list_bookings.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static '/bookings/css/bookings.css' %}">
{% endblock %}

{% block title %}Bookings{% endblock %}

{% block content %}

<div class="container mx-0 p-0">
    {% if request.user.is_staff %}
    <h1 class="text-center">All Bookings</h1>
    {% else %}
    <h1 class="text-center">Your Bookings</h1>
    {% endif %}

    <!-- Searches -->
    {% if request.user.is_staff %}
    <form method='GET' class="d-flex">
        <input class="form-control me-2 w-auto p-1 m-1" type="text" name='name' placeholder="Name"
            aria-label="Search Booking by Name" value='{{ request.GET.name }}' autocomplete="off">
        <button class="btn btn-danger p-1 m-1" type="submit">Search</button>
    </form>

    <form method='GET' class="d-flex">
        <input class="form-control me-2 w-auto p-1 m-1" type='text' name='ref' placeholder="Ref"
            aria-label="Search Booking by reference" value='{{ request.GET.ref }}' autocomplete="off">
        <button class="btn btn-danger p-1 m-1" type="submit">Search</button>
    </form>
    {% endif %}

    <form method='GET' class="d-flex">
        <!-- <input class="form-control me-2 w-auto p-1 m-1" type='date' name='date' placeholder="Date"
            aria-label="Search Bookings by date" value='{{ request.GET.date }}' autocomplete="off" class="datepicker"
            id="datepicker" type="submit"> <button class="btn btn-danger p-1 m-1" type="submit">Search</button> -->
        <input class="form-control me-2 w-auto p-1 m-1 datepicker" type='date' name='date'
            aria-label="Search Bookings by date" value='{{ request.GET.date }}' autocomplete="off"
            id="datepicker"> <button class="btn btn-danger p-1 m-1" type="submit">Search</button>
    </form>

    <!-- bookings cards -->
    <div class="card-container px-0 m-0">

        {% for booking in object_list %}

        {% if request.user.is_staff or request.user == booking.cust %}
        <div class="custom-card m-1 p-0">
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Date:</p>
                <button class="m-1 w-50">{{ booking.booking_date }}</button>
            </div>
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Time:</p>
                <button class="m-1 w-50">{{ booking.get_booking_time_display }}</button>
            </div>
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Ref:</p>
                <button class="m-1 w-50">{{ booking.pk }}</button>
            </div>
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Party of:</p>
                <button class="m-1 w-50">{{ booking.booking_party_size }}</button>
            </div>
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Name:</p>
                <button class="m-1 w-50">{{ booking.cust_name }}</button>
            </div>
            {% if request.user.is_staff %}
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Table:</p>
                <button class="m-1 w-50">{{ booking.booking_table }}</button>
            </div>
            <div class="card-row">
                <p class="ms-1 mt-1 mb-0 fw-bold">Capacity:</p>
                <button class="m-1 w-50">{{ booking.booking_table.table_num_seats }}</button>
            </div>
            {% endif %}
            <div class="buttondiv my-2 fw-bold">
                <button onclick="document.location.href='{% url 'edit_booking' booking.id %}';"
                    class="editbutton w-30 fw-bold">Edit</button>
                <button onclick="document.location.href='{% url 'delete_booking' booking.id %}';"
                    class="deletebutton w-30 fw-bold">Delete</button>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}
{% block extra_js %}
<script>
    $(function () {
        $('#datepicker').datepicker();
    });
</script>
{% endblock %}